name: xhttp
version: 0.2.0
description: A cross platform client-side HTTP library for Dart.
homepage: https://github.com/kharland/xhttp

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  build_runner: '>=1.6.2 <2.0.0'
  http_parser: ^3.1.3
  meta: '^1.1.8'
  pedantic: ^1.9.0
  quiver: ^2.1.2+1

dev_dependencies:
  test: '^1.12.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
